// Generated by IcedCoffeeScript 108.0.11
(function() {
  this.kendoGetTemplate = function(field, data) {
    var obj, template;
    template = "";
    $(".k-grid").each(function(k, grid) {
      var columns;
      columns = $(grid).data("kendoGrid").columns;
      return $.each(columns, function(k, col) {
        if (col.field === field) {
          return template = col.template;
        }
      });
    });
    template = kendo.template(template);
    if (!data) {
      return template;
    } else {
      obj = {
        data: {}
      };
      obj.data[field] = data;
      return template(obj);
    }
  };

}).call(this);
