// Generated by IcedCoffeeScript 108.0.11
(function() {
  this.kendoGetTitle = function(field) {
    var title;
    title = field;
    $(".k-grid").each(function(k, grid) {
      var columns;
      columns = $(grid).data("kendoGrid").columns;
      return $.each(columns, function(k, col) {
        if (col.field === field) {
          return title = col.title;
        }
      });
    });
    return title;
  };

}).call(this);
