// Generated by IcedCoffeeScript 108.0.11
(function() {
  this.renderMultiSelectText = function(selectListArray, attribute, char) {
    var displayText;
    if (attribute == null) {
      attribute = 'Text';
    }
    if (char == null) {
      char = ', ';
    }
    displayText = '';
    if (selectListArray && selectListArray[0]) {
      $.each(selectListArray, function(k, v) {
        return displayText += v[attribute] + char;
      });
      displayText = displayText.slice(0, -2);
    }
    return displayText;
  };

}).call(this);
