// Generated by IcedCoffeeScript 108.0.11
(function() {
  $.fn.serializeObject = function() {
    var obj;
    obj = {};
    $(this).find('select, textarea, input').each(function() {
      return obj[$(this).attr('name')] = $(this).val();
    });
    $(this).find("input[type=checkbox]").each(function() {
      obj[$(this).attr('name')] = null;
      if ($(this).is(':visible')) {
        return obj[$(this).attr('name')] = $(this).is(':checked');
      }
    });
    $(this).find('input[type=radio]').each(function() {
      var val;
      val = $('input[type=radio][name="' + $(this).attr('name') + '"]:checked').val();
      if (!val) {
        val = $('input[type=radio][name="' + $(this).attr('name') + '"][checked]').val();
      }
      return obj[$(this).attr('name')] = val;
    });
    return obj;
  };

}).call(this);
